name: pruebadespliegue

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  #prueba de despliegue laravel y react y mysql

  prueba:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd foodtrackv4/material-kit-react-main
          npm install
      - name: Run Composer
        run: |
          cd foodtrackv4/api
          composer install
      - name: Run Laravel
        run: |
          php artisan serve
      - name: Run React
        run: |
          cd foodtrackv4/material-kit-react-main
          npm start
      - name: Run MySQL
        #importa el archivo sql de la raiz llamado foodtrackv4.sql
        run: |
          mysql -u root < foodtrackv4.sql
