name: pruebadespliegue

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  #prueba de despliegue laravel y react y mysql

  prueba:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          ls -a 
          
      - name: Instalamos Composer
        run: |
          sudo apt update
          sudo apt install php-cli unzip
          cd ~
          curl -sS https://getcomposer.org/installer -o composer-setup.php
          HASH=`curl -sS https://composer.github.io/installer.sig`
          echo $HASH
          php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer

      - name: Run Composer
        run: |
          cd ..
          cd api
          composer install
      - name: Run Laravel
        run: |
          php artisan serve
      - name: Run React
        run: |
          cd foodtrackv4/material-kit-react-main
          npm start
      - name: Run MySQL
        #importa el archivo sql de la raiz llamado foodtrackv4.sql
        run: |
          mysql -u root < foodtrackv4.sql

      - name: depliegue
        run: |
          cd foodtrackv4/material-kit-react-main
          npm install 
          npm run build
          cd foodtrackv4/api
          composer install
          php artisan serve
